name: Validate PHP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Composer dependencies
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-dev-${{ hashFiles('**/composer.lock') }}

      - name: Install
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install --no-progress

  lint:
    name: Lint against PSR-12
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Composer dependencies
        id: get-vendor-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-dev-${{ hashFiles('**/composer.lock') }}

      - name: Check for dependencies
        if: steps.get-vendor-cache.outputs.cache-hit != 'true'
        run: |
          echo "No dependencies were found."
          exit 1
      - name: Run linter
        run: composer lint

  static-analysis:
    name: Run static analysis
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Composer dependencies
        id: get-vendor-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-dev-${{ hashFiles('**/composer.lock') }}

      - name: Check for dependencies
        if: steps.get-vendor-cache.outputs.cache-hit != 'true'
        run: |
          echo "No dependencies were found."
          exit 1
      - name: Run Static Analyser (PHPStan)
        run: composer analyse
